#!/bin/sh

version=$(rpm -q --qf '%{version}' system-release)
figlet -f /usr/share/figlet/small.flf Kenzanmedia
cat << EOF

    ########################################################
     Access allowed only to Kenzanmedia approved agents
    ########################################################

    Amazon Linux version: $version
    AMI Profile: {{ ami_profile }}
    https://aws.amazon.com/amazon-linux-ami/$version-release-notes/
    https://github.com/kenzanmedia/ami-roles

EOF