---

- name: Add group nexus
  group: name=nexus gid=1040 state=present
  tags:
    - system
    - nexus
    - build

- name: Add system user nexus
  user: name=nexus comment="Nexus Service" uid=1040 group=nexus
  tags:
    - system
    - nexus
    - build

- name: Make directories
  file: path=/{{ item }} state=directory owner=nexus group=nexus
  with_items:
    - "{{ nexus_home }}"
    - "{{ nexus_data }}"
  tags:
    - system
    - nexus
    - build

- name: Download Nexus
  get_url: url={{ nexus_url }} dest=/tmp/nexus.tgz
  tags:
    - system
    - nexus
    - build

- name: Extract Nexus Home
  command: tar zxf /tmp/nexus.tgz -C /{{ nexus_home }} --wildcards 'nexus-*' --strip 1
  tags:
    - system
    - nexus
    - build

- name: Update executable files
  template: src={{ nexus_home }}/{{ item }} dest=/{{ nexus_home }}/{{ item }} mode=0755 owner=nexus group=nexus
  with_items:
    - bin/nexus
    - bin/nexus.rc
    - bin/nexus.vmoptions
  tags:
    - system
    - nexus
    - build

- name: Symlink init.d
  file: src=/{{ nexus_home }}/bin/nexus dest=/etc/init.d/nexus owner=root group=root state=link
  tags:
    - config
    - nexus-config
    - build

- name: Dirs owned by user nexus
  file: path=/{{ item }} state=directory owner=nexus group=nexus mode=0755 recurse=yes
  with_items:
    - "{{nexus_home}}"
    - "{{nexus_data}}"
  tags:
    - config
    - nexus-config
    - build

- name: Enable nexus
  service: name=nexus enabled=yes
  tags:
    - system
    - nexus
    - build
