#!/bin/bash


## Source Custom options if any
if [[ -f /etc/jservice/jservice.conf ]];then
   . /etc/jservice/jservice.conf
fi

## Amazon

# Instance Id
instanceId=$(curl -s http://169.254.169.254/latest/meta-data/instance-id/)
# Availability Zone
availabilityZone=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone/)
# Region
ec2Region=${availability_zone%?}
# Cloud Environment
# Hard coded for dev right now
cloudEnvironment=development
# Cloud Domain
cloudDomain=kenzan-dev.com

# Set some defaults if not in User Data
if [ -z "$CLOUD_STACK" ];then
  cloudStack=default
fi
if [ -z "$CLOUD_APP" ];then
  cloudApp=default
fi

## Define Heap sizes

# Percent of total sytem memory to use
xmx_percent={{ xmx_percent }}
xms_percent={{ xms_percent }}

# Total system memory available
system_memory_in_mb=$(free -m | awk '/Mem:/ {print $2}')

# Xmx
xmx_memory_float=$(echo "$system_memory_in_mb*$xmx_percent"|bc)
xmx_memory=$(echo "($xmx_memory_float+0.5)/1" | bc)

# Xms
xms_memory_float=$(echo "$system_memory_in_mb*$xms_percent"|bc)
xms_memory=$(echo "($xms_memory_float+0.5)/1" | bc)


## Karyon vars

jServiceHome=/{{ jservice_home }}
jServiceData=/{{ jservice_data }}

LOG_FILE=$jServiceData/logs/jservice.log


## Java vars

JAVA_HOME=/{{ java_default }}
JAVA_CMD=$JAVA_HOME/bin/java

# export CLASSPATH=$CLASSPATH:$jServiceHome/*:$jServiceHome/lib/*

JVM_OPTIONS="$JVM_OPTIONS -Xmx${xmx_memory}m -Xms${xms_memory}m -XX:ErrorFile=/tmp/hs_err_pid%p.log -XX:-HeapDumpOnOutOfMemoryError"

# JAVA_OPTIONS="$JAVA_OPTIONS "

## CLOUD vars

 CLOUD_OPTIONS="-Deureka.datacenter=cloud \
-Dcom.netflix.karyon.eureka.datacenter.type=Amazon \
-Deureka.environment=$cloudEnvironment \
-Darchaius.deployment.environment=$cloudEnvironment \
-Darchaius.deployment.subenvironment=unstable \
-Darchaius.deployment.stack=$cloudStack \
-Darchaius.deployment.region=$ec2Region \
-Darchaius.deployment.availabilityzone=$availabilityZone \
-Darchaius.deployment.applicationId=$applicationId \
-Darchaius.deployment.serverId=$instanceId \
-Darchaius.deployment.domainName=$cloudDomain"

#$REPO_JVM_ARGS"


## JMX Configuration
# JMX_OPTIONS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=7094 -Djava.rmi.server.hostname=127.0.0.1"

JAVA_OPTIONS="$JVM_OPTIONS $JAVA_OPTIONS $CLOUD_OPTIONS $JMX_OPTIONS"


