---

- name: Checkout AWS missing tools
  git: repo="{{ aws_missing_tools_url }}" dest=/usr/share/aws-missing-tools
  tags:
    - system
    - build
    - awsmissingtools

- name: Setting up ec2-backup 
  file: src=/usr/share/aws-missing-tools/ec2-automate-backup/ec2-automate-backup.sh dest=/usr/bin/ec2-backup state=link owner=root group=root
  tags:
    - config
    - build
    - awsmissingtools
