---

- include_vars: Ubuntu.yml

- name: install unzip
  package: name=unzip state=present
  tags:
  - system
  - jenkins
  - build

- name: install openjdk7 ISSUE #31814
  package: name=openjdk-7-jre-headless state=present
  tags:
  - system
  - jenkins
  - build

- name: Add Jenkins repo key
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present
  tags:
  - system
  - jenkins
  - build

- name: Add Jenkins repository
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes
  tags:
  - system
  - jenkins
  - build

