---

- name: Install Linux Packages
  package: name={{item}} state=latest enablerepo=epel
  with_items:
    - git
    - rpmdevtools
    - python-pip
    - libxslt-devel
    - openssl-devel
    - httpd-devel
    - nginx
    - memcached
    - lftp
    - asciidoc