---

- name: Add group jetty
  group: name=jetty gid=1050 state=present
  tags:
    - system
    - jetty
    - build

- name: Add system user jetty
  user: name=jetty comment="jetty Service" uid=1050 group=jetty
  tags:
    - system
    - jetty
    - build

- name: Make directories
  file: path=/{{ item }} state=directory owner=jetty group=jetty
  with_items:
    - "{{ jetty_home }}"
    - "{{ jetty_logs }}"
    - "{{ jetty_webapps }}"
  tags:
    - system
    - jetty
    - build

- name: Symlink jetty_logs
  file: src=/{{ jetty_logs }} dest=/var/log/jetty owner=jetty group=jetty state=link
  tags:
    - system
    - jetty
    - build

- name: Download jetty
  get_url: url={{ jetty_url }} dest=/tmp/jetty_{{jetty_version}}.tgz
  tags:
    - system
    - jetty
    - build

- name: Extract jetty home
  command: "tar zxf /tmp/jetty_{{jetty_version}}.tgz -C /{{ jetty_home }} --exclude='jetty-distribution-{{jetty_version}}/webapps*' --strip 1"
  tags:
    - system
    - jetty
    - build

- name: Remove jetty test apps
  file: path=/{{ jetty_home }}{{ item }} state=absent
  with_items: jetty_remove
  tags:
    - system
    - jetty
    - build

- name: Symlink init.d
  file: src=/{{ jetty_home }}/bin/jetty.sh dest=/etc/init.d/jetty state=link mode=0755 owner=root group=root
  tags:
    - system
    - jetty
    - build
    
- name: jetty systemd config
  template: src=etc/systemd/system/jetty.service dest=/etc/systemd/system/jetty.service owner=root group=root mode=0755
  when: ansible_os_family == 'Debian'

  tags:
  - system
  - build
  - base
  - config

- name: Symlink webapps
  file: src=/{{ jetty_webapps }} dest=/{{ jetty_home }}/webapps state=link mode=0755 owner=jetty group=jetty
  tags:
    - system
    - jetty
    - build

- name: Jetty config
  template: src=etc/default/jetty dest=/etc/default/jetty mode=0644 owner=root group=root
  tags:
    - config
    - jetty-config
    - build

- name: Logback config
  template: src=etc/default/logback.xml dest=/etc/default/logback.xml mode=0644 owner=root group=root
  tags:
    - config
    - logback-config
    - build

- name: Dirs owned by user jetty
  file: path=/{{ item }} state=directory owner=jetty group=jetty mode=0755 recurse=yes
  with_items:
    - "{{jetty_home}}"
    - "{{jetty_data}}"
  tags:
    - config
    - jetty-config
    - build

#- name: Enable jetty
#  service: name=jetty enabled=yes
#  tags:
#    - system
#    - jetty
#    - build

- name: Local Ansible facts
  template: src={{ role_local_facts }}/jetty9.fact dest=/{{ role_local_facts }}/jetty9.fact owner=root group=root mode=0644
  tags:
    - config
    - jetty-config
    - facts
    - build
