---

- name: Add group jetty
  group: name=jetty gid=1050 state=present
  tags:
    - system
    - jetty
    - build

- name: Add system user jetty
  user: name=jetty comment="jetty Service" uid=1050 group=jetty
  tags:
    - system
    - jetty
    - build

- name: Make directories
  file: path=/{{ item }} state=directory owner=jetty group=jetty
  with_items:
    - "{{ jetty_home }}"
    - "{{ jetty_logs }}"
    - "{{ jetty_webapps }}"
  tags:
    - system
    - jetty
    - build

- name: Symlink jetty_logs
  file: src=/{{ jetty_logs }} dest=/var/log/jetty owner=jetty group=jetty state=link
  tags:
    - system
    - jetty
    - build

- name: Remove jetty test apps
  file: path=/{{ jetty_home }}{{ item }} state=absent
  with_items: jetty_remove
  tags:
    - system
    - jetty
    - build

- name: Symlink webapps
  file: src=/{{ jetty_webapps }} dest=/{{ jetty_home }}/webapps state=link mode=0755 owner=jetty group=jetty
  tags:
    - system
    - jetty
    - build

- name: Jetty config
  template: src=etc/default/jetty dest=/etc/default/jetty mode=0644 owner=root group=root
  tags:
    - config
    - jetty-config
    - build

- name: Logback config
  template: src=etc/default/logback.xml dest=/etc/default/logback.xml mode=0644 owner=root group=root
  tags:
    - config
    - logback-config
    - build

- name: Dirs owned by user jetty
  file: path=/{{ item }} state=directory owner=jetty group=jetty mode=0755 recurse=yes
  with_items:
    - "{{jetty_home}}"
    - "{{jetty_data}}"
  tags:
    - config
    - jetty-config
    - build

- name: Setup Amazon linux
  include: Amazon.yml
  when: ansible_distribution == 'Amazon'
  tags:
    - system
    - jetty
    - build

- name: Setup Ubuntu
  include: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags:
    - system
    - jetty
    - build

- name: Local Ansible facts
  template: src={{ role_local_facts }}/jetty8.fact dest=/{{ role_local_facts }}/jetty8.fact owner=root group=root mode=0644
  tags:
    - config
    - jetty-config
    - facts
    - build
