---

- name: Remove packer key
  lineinfile: dest=/home/ec2-user/.ssh/authorized_keys state=absent regexp='(.*)packer(.*)'
  tags:
  - config
  - build
  - postrun-config

- name: AMI Profile
  template: src={{ kenzanmedia_etc }}/ami_profile dest=/{{ kenzanmedia_etc }}/ami_profile owner=root group=root mode=0755
  tags:
  - config
  - build
  - postrun-config

- name: Local Ansible facts
  template: src={{ role_local_facts }}/ami_profile.fact dest=/{{ role_local_facts }}/ami_profile.fact owner=root group=root mode=0644
  tags:
  - config
  - build
  - postrun-config

- name: Assemble facts
  assemble: src=/{{ role_local_facts }} dest=/etc/ansible/facts.d/kenzanmedia.fact
  tags:
  - config
  - build
  - postrun-config

- name: Enable instance_conf
  service: name=instance_conf enabled=yes
  when: ansible_os_family == 'RedHat'
  tags:
  - system
  - build
  - base
  - instance_conf