---

- name: Stopping jetty service
  service: name=jetty state=stopped

- name: Download snapshot build of Edda from cloudbees
  get_url: url={{ latest_successful_build_url }} dest=/{{ jetty_webapps }}/edda.war owner=jetty group=jetty
  tags: build

- name: Create Edda directory
  file: path=/{{ edda_home }} state=directory owner=jetty group=jetty
  tags: build

- name: Starting jetty service
  service: name=jetty state=started