---

- name: restart haproxy
  service: name=haproxy state=restarted
  when: update

- name: reload haproxy
  service: name=haproxy state=reloaded
  when: update

- name: start haproxy
  service: name=haproxy state=started

- name: stop haproxy
  service: name=haproxy state=stopped

- name: enable haproxy
  shell: /bin/echo "ENABLED=1" >> /etc/default/haproxy
