---
repos:
  - kenzanmedia-main.repo

packages:
  - python-pip
  - unzip
  - zip
  - screen
  - ntp
  - telnet
  - mlocate
  - figlet
  - nmap
  - lynx
  - python-magic
  - bc
  - git

#to foward syslog to graylog
graylog_host: graylogger.us-west-2.???
graylog_port: 9899

# Update only security packages via cron (daily,weekly,monthly,yearly)
security_update_schedule: weekly

dirs:
  - "/{{ role_local_facts }}"
  - "/etc/ansible/facts.d"
  - "/{{ kenzanmedia_etc }}/instance_conf.d"

